### ISSUE TITLE
Balance data on the food balance data did not read well on my trial

### ISSUE THREAD

**Issue by otwani** [BjnNowak/CultivatedPlanet#1]
Hi Ben,
I tried to replicate your code but failed to run the food balance part as it did not find the columns. i suppose may be the data did not read in well. How can I remedy this.

**Comment by BjnNowak** [comment]
Hi Otwani,

Thanks for the feedback. I changed the URL of the 'balance' table in the script, could you confirm me it's working now?

**Comment by otwani** [comment]
Hi Ben,
Yes thanks. Worked well.

I am now trying to generate a map only for sorghum. Any ideas.

Kind regards,
Daniel

**Comment by BjnNowak** [comment]
Great, you may use only the mapping() function created in the script to draw a single map.
Best,
Ben
